version: 2.1

workflows:
    on-pull-request-update:
      jobs:
        - install-dependencies:
            filters:
              branches:
                ignore: master
        - lint-unit-test:
            requires:
              - install-dependencies
            filters:
              branches:
                ignore: master

    on-master-merge:
      jobs:
        - install-dependencies:
            filters:
              branches:
                only: master
        - compile-package:
            requires:
              - install-dependencies
            filters:
              branches:
                only: master


jobs:
  install-dependencies:
    docker:
      - image: circleci/node:lts
    working_directory: ~/node-static-frontend-server
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-{{ checksum "package-lock.json" }}

  lint-unit-test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/node-static-frontend-server
    steps:
      - attach_workspace:
          at: .
      - run: npm run lint

  compile-package:
    docker:
      - image: circleci/node:lts
    working_directory: ~/node-static-frontend-server
    steps:
      - attach_workspace:
          at: .
      - run: npm install pkg
      - run: pkg --target node12-linux .
